import '../styles/globals.css'
import Head from 'next/head';
import { useState, useEffect, createContext } from 'react';

export const WindowSizeContext = createContext();
// UseWindowsHook................
const useWindowSize = () => {
  const [windowSize, setWindowSize] = useState({ width: undefined, height: undefined });
  useEffect(() => {
    // Handler to call on window resize
    function handleResize() {
      setWindowSize({ width: window.innerWidth, height: window.innerHeight });
    }
    window.addEventListener("resize", handleResize);
    handleResize();

    // Remove event listener on cleanup
    return () => window.removeEventListener("resize", handleResize);
  }, []); // Empty array ensures that effect is only run on mount
  return windowSize;
}


function MyApp({ Component, pageProps }) {
  const windowSize = useWindowSize();
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <title>Surprisingly Bata – batabd</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1,user-scalable=0,minimul-ui" />
        {/* <meta name="viewport" content="width=device-width,initial-scale=1.0"/> */}
        {/* <meta name="viewport" content="initial-scale=1, maximum-scale=1"/> */}

        <link rel="shortcut icon" href="//cdn.shopify.com/s/files/1/2287/9679/files/bata_43866b82-8696-433a-bd50-0036cd4dfb2d_32x32.png?v=1527415145" type="image/png" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"></link>
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300&display=swap" rel="stylesheet"></link>

        {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossOrigin="anonymous"></link> */}
        {/* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossOrigin="anonymous"></script> */}

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" crossOrigin="anonymous" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" crossOrigin="anonymous"></script>
      </Head>
      <WindowSizeContext.Provider value={[windowSize]}>
        <Component {...pageProps} />
      </WindowSizeContext.Provider>
    </>
  )
}

export default MyApp
