let newProduct = [
    { id: 1, category: 'Sports', img: '/newProduct/sports/1.jpg', size: '7 8 9', model: 'POWER', desc: 'Power Cric Sporty Sneaker for Men', star: '0', price: 'Tk. 2699.00', color: 'Black' },
    { id: 2, category: 'Sports', img: '/newProduct/sports/2.jpg', size: '6 7 8 9', model: 'POWER', desc: 'Power Wave Molle Blue Sneaker for Men', star: '1', price: 'Tk. 2339.00', color: 'Blue' },
    { id: 3, category: 'Sports', img: '/newProduct/sports/3.jpg', size: '8 9', model: 'POWER', desc: 'Power Lace-up Sports Shoe for Men', star: '5', price: 'Tk. 2099.00', color: 'Brown' },
    { id: 4, category: 'Sports', img: '/newProduct/sports/4.jpg', size: '6 7 8 9', model: 'POWER', desc: 'Power Wave Molle Blue Sneaker for Men', star: '3', price: 'Tk. 2519.00', color: 'Blue' },
    { id: 5, category: 'Sports', img: '/newProduct/sports/5.jpg', size: '7  9', model: 'POWER', desc: "Sparx Fernando Men's Sneaker", star: '4', price: 'Tk. 4439.00', color: 'Black' },
    { id: 6, category: 'Sports', img: '/newProduct/sports/6.jpg', size: '7 8', model: 'POWER', desc: "Sparx Fernando Men's Sneaker", star: '0', price: 'Tk. 5439.00', color: 'Blue' },
    { id: 7, category: 'Casuals', img: '/newProduct/casuals/1.jpg', size: '6 7 8 9', model: 'BATA', desc: "Bata Men's Versace Loafer", star: '1', price: 'Tk. 4099.00', color: 'Blue' },
    { id: 8, category: 'Casuals', img: '/newProduct/casuals/2.jpg', size: '10', model: 'Bata Red Label', desc: 'Bata Red Label Sheldon Casual Shoe', star: '3', price: 'Tk. 2539.00', color: 'Brown' },
    { id: 9, category: 'Casuals', img: '/newProduct/casuals/3.jpg', size: '6 7 8 9', model: 'Bata Red Label', desc: 'Bata Red Label Sheldon Casual Shoe', star: '5', price: 'Tk. 3099.00', color: 'Black' },
    { id: 10, category: 'Casuals', img: '/newProduct/casuals/4.jpg', size: '8 9', model: 'Bata Red Label', desc: 'Bata Red Label Lawson Lace-Up Casual Shoe', star: '4', price: 'Tk. 2619.00', color: 'Blue' },
    { id: 11, category: 'Casuals', img: '/newProduct/casuals/5.jpg', size: '6 7', model: 'North Star', desc: "North Star Men's Casual Sneaker", star: '4', price: 'Tk. 2439.00', color: 'Blue' },
    { id: 12, category: 'Casuals', img: '/newProduct/casuals/6.jpg', size: '6 7 8 9', model: 'Weinbrenner', desc: "Bata Casual Moccasin in Black", star: '1', price: 'Tk. 1500.00', color: 'Black' },
    { id: 13, category: 'LadiesFlats', img: '/newProduct/LadiesFlats/1.jpg', size: '3 4 5', model: 'Hush Puppies', desc: "Hush Puppies Danica Women's Sandal", star: '0', price: 'Tk. 2799.00', color: 'Blue' },
    { id: 14, category: 'LadiesFlats', img: '/newProduct/LadiesFlats/2.jpg', size:'3 4 5', model: 'Hush Puppies', desc: "Hush Puppies Danica Women's Sandal", star: '2', price: 'Tk. 2939.00', color: 'Brown' },
    { id: 15, category: 'LadiesFlats', img: '/newProduct/LadiesFlats/3.jpg', size: '3 4 5', model: 'Hush Puppies', desc: "Hush Puppies Danica Women's Sandal", star: '5', price: 'Tk. 2599.00', color: 'Black' },
    { id: 16, category: 'LadiesFlats', img: '/newProduct/LadiesFlats/4.jpg', size: '3 4 5', model: 'Bata comfit', desc: 'Comfit Callie Sandal for Women', star: '1', price: 'Tk. 2119.00', color: 'Black' },
    { id: 17, category: 'LadiesFlats', img: '/newProduct/LadiesFlats/5.jpg', size: '3 4 5', model: 'Light & Easy', desc: "Comfit Orchid Dual Strap Sandal for Women", star: '4', price: 'Tk. 3439.00', color: 'Blue' },
    { id: 18, category: 'LadiesFlats', img: '/newProduct/LadiesFlats/6.jpg', size: '3 4 5', model: 'Bata comfit', desc: " Comfit Catin Sandal for Women", star: '0', price: 'Tk. 1739.00', color: 'Black' },
    { id: 19, category: 'Sandals', img: '/newProduct/Sandals/1.jpg', size: '6 7 8 9', model: 'Bata', desc: "Hush Puppies Danica Women's Sandal", star: '1', price: 'Tk. 2399.00', color: 'Blue' },
    { id: 20, category: 'Sandals', img: '/newProduct/Sandals/2.jpg', size: '6 7 8 9', model: 'Bata', desc: "Hush Puppies Danica Women's Sandal", star: '3', price: 'Tk. 2139.00', color: 'Brown' },
    { id: 21, category: 'Sandals', img: '/newProduct/Sandals/3.jpg', size: '6 7 8 9', model: 'Hush Puppies', desc: "Hush Puppies Danica Women's Sandal", star: '5', price: 'Tk. 6099.00', color: 'Black' },
    { id: 22, category: 'Sandals', img: '/newProduct/Sandals/4.jpg', size: '6 7 8 9', model: 'Hush Puppies', desc: 'Comfit Callie Sandal for Women', star: '4', price: 'Tk. 3519.00', color: 'Blue' },
    { id: 23, category: 'Sandals', img: '/newProduct/Sandals/5.jpg', size: '6 7 8 9', model: 'Bata', desc: "Comfit Orchid Dual Strap Sandal for Women", star: '2', price: 'Tk. 1939.00', color: 'Blue' },
    { id: 24, category: 'Sandals', img: '/newProduct/Sandals/6.jpg', size: '6 7 8 9', model: 'Bata ', desc: " Comfit Catin Sandal for Women", star: '0', price: 'Tk. 1889.00', color: 'Black' },
    { id: 25, category: 'Formal', img: '/newProduct/Formal/1.jpg', size: '6 7 8 9', model: 'Bata', desc: "Bata Big Day Crocodile-Effect Shoe for Men", star: '1', price: 'Tk. 5999.00', color: 'Blue' },
    { id: 26, category: 'Formal', img: '/newProduct/Formal/2.jpg', size:'6 7 8 9', model: 'Bata', desc: "Bata Big Day Shoe for Men", star: '3', price: 'Tk. 5839.00', color: 'Brown' },
    { id: 27, category: 'Formal', img: '/newProduct/Formal/3.jpg', size: '6 7 8 9', model: 'Amabassador', desc: "Ambassador TENEESY DERBY Formal Lace-up Shoe for Men", star: '5', price: 'Tk. 4799.00', color: 'Black' },
    { id: 28, category: 'Formal', img: '/newProduct/Formal/4.jpg', size: '6 7 8 9', model: 'Amabassador', desc: 'Ambassador TENEESY DERBY Formal Lace-up Shoe for Men', star: '1', price: 'Tk. 3819.00', color: 'Blue' },
    { id: 29, category: 'Formal', img: '/newProduct/Formal/5.jpg', size: '6 7 8 9', model: 'Hush Puppies', desc: "Comfit Orchid Dual Strap Sandal for Women", star: '4', price: 'Tk. 4839.00', color: 'Blue' },
    { id: 30, category: 'Formal', img: '/newProduct/Formal/6.jpg', size: '6 7 8 9', model: 'Hush Puppies ', desc: " Comfit Catin Sandal for Women", star: '2', price: 'Tk. 8439.00', color: 'Black' },
    { id: 31, category: 'Accessories', img: '/newProduct/Accessories/6.jpg', size:'6 7 8 9', model: 'Bata ', desc: " Comfit Catin Sandal for Women", star: '1', price: 'Tk. 1439.00', color: 'Black' },
    { id: 32, category: 'Accessories', img: '/newProduct/Accessories/1.jpg', size: '6 7 8 9', model: 'Bata', desc: "Bata Big Day Crocodile-Effect Shoe for Men", star: '5', price: 'Tk. 4699.00', color: 'Blue' },
    { id: 33, category: 'Accessories', img: '/newProduct/Accessories/2.jpg', size: '6 7 8 9', model: 'Bata', desc: "Bata Big Day Shoe for Men", star: '3', price: 'Tk. 8839.00', color: 'Brown' },
    { id: 34, category: 'Accessories', img: '/newProduct/Accessories/3.jpg', size: '6 7 8 9', model: 'Amabassador', desc: "Ambassador TENEESY DERBY Formal Lace-up Shoe for Men", star: '5', price: 'Tk. 5699.00', color: 'Black' },
    { id: 35, category: 'Accessories', img: '/newProduct/Accessories/4.jpg', size: '6 7 8 9', model: 'Amabassador', desc: 'Ambassador TENEESY DERBY Formal Lace-up Shoe for Men', star: '2', price: 'Tk. 8819.00', color: 'Blue' },
    { id: 36, category: 'Accessories', img: '/newProduct/Accessories/5.jpg', size: '6 7 8 9', model: 'Hush Puppies', desc: "Comfit Orchid Dual Strap Sandal for Women", star: '4', price: 'Tk. 9839.00', color: 'Blue' }
];
export default newProduct;